name: Build java service

on:
  workflow_call:

jobs:
 
  compile:
 
    name: Compile code
    runs-on: ubuntu-latest

    steps:
      - run: echo "Compile java code"

  testing:
 
    name: Run jUnit tests
    runs-on: ubuntu-latest
    needs:
    - compile

    steps:
      - run: echo "Testing java code"
