name: Wait for deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
      docker_tag:
        type: string

  workflow_dispatch:
    inputs:
      environment:
        type: environment
      docker_tag:
        type: string
jobs:
 
  wait:
 
    name: Wait for deployment to `${{ inputs.environment }}`
    runs-on: ubuntu-latest

    steps:
      - run: echo "Check is '${{ inputs.docker_tag }}' is deployd to '${{ inputs.environment }}'"